# Dataset
root: /home/martin/school/4B/MSCI_446/AVP_Dataset/processed_dataset

# Transform params
n_fft: 2048
hop_length: 512
n_mels: 128

# Model
model_name: resnet18
pretrained: False

# Training
epochs: 60
lr: 4.0e-4
weight_decay: 5.0e-4
eps: 1.0e-7
batch_size: 256
num_workers: 12

